// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function customDouble(foo) {
  return (foo << 1);
}

function customTriple(foo) {
  return Math.imul(foo, 3);
}

((var a = 1));

var mode2 = "dev";

exports.mode2 = mode2;
exports.customDouble = customDouble;
exports.customTriple = customTriple;
/*  Not a pure module */
