// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Book = require("Book");
var MySchool = require("MySchool");

var johnName = MySchool.john.name;

var johnName1 = MySchool.john1.name;

var i32arr = new Int32Array(3);

i32arr[0] = 42;

console.log(i32arr[0]);

var date = new Date();

var myBook = new Book();

exports.johnName = johnName;
exports.johnName1 = johnName1;
exports.i32arr = i32arr;
exports.date = date;
exports.myBook = myBook;
/* johnName Not a pure module */
