// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

Curry._2(document.addEventListener, "mouseup", (function (_event) {
        console.log("Clicked!");
        
      }));

var loc = document.location;

document.location.href = "rescript-lang.org";

exports.loc = loc;
/*  Not a pure module */
