// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var newScore = 20;

var message = "hello word";

console.log("Enjoying the docs so far?");

console.log("hello");

console.log(1);

var A = {
  b: 4
};

var B = {
  b: 4
};

var greeting = "hello!";

var score = 10;

var displayGreeting = true;

var result = 1;

exports.greeting = greeting;
exports.score = score;
exports.newScore = newScore;
exports.message = message;
exports.displayGreeting = displayGreeting;
exports.result = result;
exports.A = A;
exports.B = B;
/*  Not a pure module */
