// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var myValue = {
  contents: 5
};

var five = myValue.contents;

myValue.contents = 6;

myValue.contents = 6;

exports.myValue = myValue;
exports.five = five;
/*  Not a pure module */
