// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");
var MyIdValidator = require("MyIdValidator");

var licenseNumber = 5;

if (licenseNumber !== undefined) {
  console.log("The person's license number is " + licenseNumber.toString());
} else {
  console.log("The person doesn't have a car");
}

var personId = "abc123";

var result = MyIdValidator.validate(personId);

var personHasACar = true;

var x = 5;

var x2 = Caml_option.some(undefined);

exports.personHasACar = personHasACar;
exports.licenseNumber = licenseNumber;
exports.x = x;
exports.x2 = x2;
exports.personId = personId;
exports.result = result;
/*  Not a pure module */
