// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var name = "Joe";

var greeting1 = "Hello\nWorld\n👍\n" + name + "\n";

var message = "Today I am " + 10 + " years old.";

var r = /b/g;

var floatCal = 0.5 + 0.6;

var greeting = "Hello world!";

var multilineGreeting = "Hello\n  Hi World!";

var greetings = "Hello earth!";

var age = 10;

var firstLetterOfAlphabet = /* 'a' */97;

var test;

exports.greeting = greeting;
exports.multilineGreeting = multilineGreeting;
exports.greetings = greetings;
exports.name = name;
exports.greeting1 = greeting1;
exports.age = age;
exports.message = message;
exports.firstLetterOfAlphabet = firstLetterOfAlphabet;
exports.r = r;
exports.floatCal = floatCal;
exports.test = test;
/* No side effect */
