// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Greeting = require("./Greeting.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Greeting.make, {}));
}

var make = App;

exports.make = make;
/* react Not a pure module */
