// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var numbers = [
  1,
  2,
  3,
  4,
  5
];

var items = Belt_Array.map(numbers, (function (number) {
        return React.createElement("li", {
                    key: String(number)
                  }, number);
      }));

var todos = [
  {
    id: "todo1",
    text: "Todo 1"
  },
  {
    id: "todo2",
    text: "Todo 2"
  }
];

var items1 = Belt_Array.map(todos, (function (todo) {
        return React.createElement("li", {
                    key: todo.id
                  }, todo.text);
      }));

function ArraysAndKeys$Blog(Props) {
  var posts = Props.posts;
  var sidebar = React.createElement("ul", undefined, Belt_Array.map(posts, (function (post) {
              return React.createElement("li", {
                          key: post.id
                        }, post.title);
            })));
  var content = Belt_Array.map(posts, (function (post) {
          return React.createElement("div", {
                      key: post.id
                    }, React.createElement("h3", undefined, post.title), React.createElement("p", undefined, post.content));
        }));
  return React.createElement("div", undefined, sidebar, React.createElement("hr", undefined), content);
}

var Blog = {
  make: ArraysAndKeys$Blog
};

var posts = [
  {
    id: "1",
    title: "Hello World",
    content: "Welcome to learning ReScript & React!"
  },
  {
    id: "2",
    title: "Installation",
    content: "You can install reason-react from npm."
  }
];

var blog = React.createElement(ArraysAndKeys$Blog, {
      posts: posts
    });

exports.numbers = numbers;
exports.items = items;
exports.todos = todos;
exports.items1 = items1;
exports.Blog = Blog;
exports.posts = posts;
exports.blog = blog;
/* items Not a pure module */
