// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var FriendStatusHook = require("./FriendStatusHook.bs.js");

var ChatAPI = {};

function useFriendStatus(friendId) {
  var match = React.useState(function () {
        return /* Offline */0;
      });
  var setState = match[1];
  React.useEffect(function () {
        var handleStatusChange = function (status) {
          return Curry._1(setState, (function (param) {
                        if (status.isOnline) {
                          return /* Online */2;
                        } else {
                          return /* Offline */0;
                        }
                      }));
        };
        subscribeToFriendStatus(friendId, handleStatusChange);
        Curry._1(setState, (function (param) {
                return /* Loading */1;
              }));
        return (function (param) {
                  unsubscribeFromFriendStatus(friendId, handleStatusChange);
                  
                });
      });
  return match[0];
}

function BuildACustomHook(Props) {
  var friend = Props.friend;
  var onlineState = FriendStatusHook.useFriendStatus(friend.id);
  switch (onlineState) {
    case /* Offline */0 :
        return "Offline";
    case /* Loading */1 :
        return "Loading";
    case /* Online */2 :
        return "Online";
    
  }
}

function BuildACustomHook$make1(Props) {
  var friend = Props.friend;
  var onlineState = FriendStatusHook.useFriendStatus(friend.id);
  var color;
  switch (onlineState) {
    case /* Offline */0 :
        color = "red";
        break;
    case /* Loading */1 :
        color = "grey";
        break;
    case /* Online */2 :
        color = "green";
        break;
    
  }
  return React.createElement("li", {
              style: {
                color: color
              }
            }, friend.name);
}

var make = BuildACustomHook;

var make1 = BuildACustomHook$make1;

exports.ChatAPI = ChatAPI;
exports.useFriendStatus = useFriendStatus;
exports.make = make;
exports.make1 = make1;
/* react Not a pure module */
