// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ComponentsAndProps(Props) {
  return React.createElement("div", undefined, "Hello ReScripters!");
}

function ComponentsAndProps$make1(Props) {
  var title = Props.title;
  var visitorCount = Props.visitorCount;
  var children = Props.children;
  var visitorCountMsg = "You are visitor number: " + String(visitorCount);
  return React.createElement("div", undefined, React.createElement("div", undefined, title), React.createElement("div", undefined, visitorCountMsg), children);
}

function ComponentsAndProps$make2(Props) {
  var name = Props.name;
  var greeting = name !== undefined ? "Hello " + name + "!" : "Hello stranger!";
  return React.createElement("div", undefined, greeting);
}

function ComponentsAndProps$make3(Props) {
  var onClick = Props.onClick;
  var msg = Props.msg;
  var children = Props.children;
  return React.createElement("div", {
              onClick: onClick
            }, msg, children);
}

function make(props) {
  return React.createElement("a", {
              href: props.href
            }, props.children);
}

var Link = {
  make: make
};

function ComponentsAndProps$Label(Props) {
  var title = Props.title;
  return React.createElement("div", {
              className: "myLabel"
            }, title);
}

var Label = {
  make: ComponentsAndProps$Label
};

function ComponentsAndProps$make4(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, React.createElement(ComponentsAndProps$Label, {
                  title: "Getting Started"
                }), children);
}

var make$1 = ComponentsAndProps;

var make1 = ComponentsAndProps$make1;

var make2 = ComponentsAndProps$make2;

var make3 = ComponentsAndProps$make3;

var make4 = ComponentsAndProps$make4;

exports.make = make$1;
exports.make1 = make1;
exports.make2 = make2;
exports.make3 = make3;
exports.Link = Link;
exports.Label = Label;
exports.make4 = make4;
/* react Not a pure module */
