// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_splice_call = require("rescript/lib/js/caml_splice_call.js");

var element = React.createElement("h1", undefined, "Hello World");

function wrapChildren(children) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Overview"), children);
}

var greeting = "Hello ";

var element1 = React.createElement("div", {
      className: "myElement"
    }, greeting, "Stranger");

var element2 = [
  "element 1",
  "element 2",
  "element 3"
];

var name = "Andrea";

var element3 = name !== undefined ? React.createElement("div", undefined, "Hello " + name) : null;

var result = React.createElement("div", undefined, element3);

function render(myComp) {
  return React.createElement("div", undefined, React.createElement(myComp, {
                  name: "Franz"
                }));
}

function render1(article) {
  var children = [
    "Introduction",
    "Body"
  ];
  var props1 = {
    title: "Article #1",
    children: null
  };
  return Caml_splice_call.spliceApply(React.createElement, [
              article,
              props1,
              children
            ]);
}

var createDom = React.createElement("div", {
      className: "card"
    });

var original = React.createElement("div", {
      className: "hello"
    });

var clone = React.cloneElement(original, {
      className: "world",
      "data-name": "some name"
    });

var str = "Hello";

var number = 1;

var numberFloat = 1.0;

exports.element = element;
exports.wrapChildren = wrapChildren;
exports.greeting = greeting;
exports.element1 = element1;
exports.str = str;
exports.number = number;
exports.numberFloat = numberFloat;
exports.element2 = element2;
exports.name = name;
exports.element3 = element3;
exports.result = result;
exports.render = render;
exports.render1 = render1;
exports.createDom = createDom;
exports.original = original;
exports.clone = clone;
/* element Not a pure module */
