// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function greet(name) {
  return "Hello " + name;
}

function greetMore(name) {
  return "Hello " + name;
}

function addCoordinates(x, y) {
  return x + y | 0;
}

function drawCircle(r, c) {
  console.log("color: " + c);
  return Math.imul(r, r);
}

var circle = drawCircle(10, "red");

function startAt(r1, r2) {
  return Math.imul(r1, r2);
}

function drawCircle2(color, radius, param) {
  console.log("color: " + color);
  if (radius !== undefined) {
    return Math.imul(radius, radius);
  } else {
    return 1;
  }
}

function drawCircle3(color, radius, param) {
  console.log("color: " + color);
  if (radius !== undefined) {
    return Math.imul(radius, radius);
  } else {
    return 1;
  }
}

function drawCircle4(radiusOpt, color, param) {
  var radius = radiusOpt !== undefined ? radiusOpt : 0;
  console.log("color: " + color);
  return Math.imul(radius, radius);
}

function neverTerminate(_param) {
  while(true) {
    _param = undefined;
    continue ;
  };
}

function listHas(_list, item) {
  while(true) {
    var list = _list;
    if (!list) {
      return false;
    }
    if (list.hd === item) {
      return true;
    }
    _list = list.tl;
    continue ;
  };
}

function callSecond(_param) {
  while(true) {
    _param = undefined;
    continue ;
  };
}

function callFirst(_param) {
  while(true) {
    _param = undefined;
    continue ;
  };
}

function add1(x, y) {
  return x + y | 0;
}

var re = add1(1, 2);

function echo(a) {
  return a;
}

echo(undefined);

var result = "Hello World!";

var sum = 6;

var add = 11;

exports.greet = greet;
exports.result = result;
exports.sum = sum;
exports.greetMore = greetMore;
exports.addCoordinates = addCoordinates;
exports.add = add;
exports.drawCircle = drawCircle;
exports.circle = circle;
exports.startAt = startAt;
exports.drawCircle2 = drawCircle2;
exports.drawCircle3 = drawCircle3;
exports.drawCircle4 = drawCircle4;
exports.neverTerminate = neverTerminate;
exports.listHas = listHas;
exports.callSecond = callSecond;
exports.callFirst = callFirst;
exports.add1 = add1;
exports.re = re;
exports.echo = echo;
/* circle Not a pure module */
