// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ComponentsAndProps = require("./ComponentsAndProps.bs.js");

function Greeting(Props) {
  var name = Props.name;
  var greeting = name !== undefined ? "Hello " + name + "!" : "Hello stranger!";
  return React.createElement("div", undefined, React.createElement("div", undefined, greeting), React.createElement(ComponentsAndProps.Label.make, {
                  title: "Test"
                }));
}

var Label;

var make = Greeting;

exports.Label = Label;
exports.make = make;
/* react Not a pure module */
