// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var message = "Good morning!";

function calls(param) {
  console.log("Wow! morning");
  
}

console.log("Wow! morning");

console.log("Wow! morning");

var message1 = "Good morning";

for(var i = 1; i <= 10; ++i){
  console.log(i);
}

for(var i$1 = 10; i$1 >= 1; --i$1){
  console.log(i$1);
}

var $$break = {
  contents: false
};

while(!$$break.contents) {
  if (Math.random() > 0.3) {
    $$break.contents = true;
  } else {
    console.log("Still running");
  }
};

var isMorning = true;

var one = 1;

var ten = 10;

exports.isMorning = isMorning;
exports.message = message;
exports.calls = calls;
exports.message1 = message1;
exports.one = one;
exports.ten = ten;
exports.$$break = $$break;
/*  Not a pure module */
