// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var School = require("./School.bs.js");

var studentMessage = School.message;

exports.studentMessage = studentMessage;
/* No side effect */
