// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var MyJSFile = require("MyJSFile");

var me = {
  age: 5,
  name: "Big ReScript"
};

var me1 = {
  age: "hello!",
  name: "Big ReScript"
};

var age = me.age;

MyJSFile.student1.name = "Mary";

var myPoint = {
  x: 1.0,
  y: 2.0,
  z: 3.0
};

Curry._2(document.addEventListener, "mouseup", (function (_event) {
        console.log("Clicked!");
        
      }));

var loc = document.location;

document.location.href = "rescript-lang.org";

exports.me = me;
exports.me1 = me1;
exports.age = age;
exports.myPoint = myPoint;
exports.loc = loc;
/* age Not a pure module */
