// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log(10);

function displayMessage(m) {
  console.log(m._0);
  
}

displayMessage(/* Success */{
      _0: "You did it!"
    });

var myArray = [
  1,
  2,
  3
];

if (myArray.length !== 3) {
  throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "PatternMatchingAndDestructuring.res",
          41,
          4
        ],
        Error: new Error()
      };
}

var item1 = myArray[0];

var item2 = myArray[1];

var data = {
  TAG: /* GoodResult */1,
  _0: "Product shipped!"
};

if (typeof data === "number") {
  console.log("Bah.");
} else if (data.TAG === /* BadResult */0) {
  console.log("Something's wrong. The error code is: " + "Product shipped!".toString());
} else {
  console.log("Success! Product shipped!");
}

var coordinates = [
  10,
  20,
  30
];

var x = 10;

var student1 = {
  name: "John",
  age: 10
};

var name = "John";

var myResult = /* Success */{
  _0: "You did it!"
};

var message = "You did it!";

var n = "John";

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

exports.coordinates = coordinates;
exports.x = x;
exports.student1 = student1;
exports.name = name;
exports.myResult = myResult;
exports.message = message;
exports.displayMessage = displayMessage;
exports.n = n;
exports.myArray = myArray;
exports.item1 = item1;
exports.item2 = item2;
exports.myList = myList;
exports.data = data;
/*  Not a pure module */
