// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var me = {
  age: 27,
  name: "seungmin"
};

function validateAge(age) {
  if (age === 0) {
    return "Nothing Info";
  } else {
    return "Match age" + age.toString();
  }
}

function getAge(age) {
  return age;
}

function parseData(who) {
  if (who.name === "seungmin") {
    return who.age;
  } else {
    return 0;
  }
}

var result = validateAge(parseData(me));

var pipeResult = validateAge(parseData(me));

var result1 = [
      1,
      2,
      3
    ].map(function (a) {
        return a + 1 | 0;
      }).filter(function (a) {
      return a % 2 === 0;
    });

asyncRequest().setWaitDuration(4000).send();

var result2 = [
      1,
      2,
      3
    ].map(function (a) {
        return a + 1 | 0;
      }).filter(function (a) {
      return a % 2 === 0;
    });

asyncRequest().setWaitDuration(4000).send();

function add3(a, b, c) {
  return (a + b | 0) + c | 0;
}

function addTo7(x) {
  return add3(3, x, 4);
}

function addTo7_(__x) {
  return add3(3, __x, 4);
}

function getName(me) {
  return me.name;
}

function namePerson(age, name) {
  return name + age.toString();
}

var result3 = "seungmin" + (27).toString();

exports.me = me;
exports.validateAge = validateAge;
exports.getAge = getAge;
exports.parseData = parseData;
exports.result = result;
exports.pipeResult = pipeResult;
exports.result1 = result1;
exports.result2 = result2;
exports.add3 = add3;
exports.addTo7 = addTo7;
exports.addTo7_ = addTo7_;
exports.getName = getName;
exports.namePerson = namePerson;
exports.result3 = result3;
/* result Not a pure module */
