// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var meNextYear = {
  age: 6,
  name: "Big ReScript"
};

var baby = {
  name: "Baby ReScript",
  age: 5
};

baby.age = baby.age + 1 | 0;

function getAge(entity) {
  return entity.age;
}

var me1 = {
  name: "Baby ReScript",
  age: 5
};

var me = {
  age: 5,
  name: "Big ReScript"
};

var you = {
  age: 20,
  name: "Big ReScript"
};

var name = "Big ReScript";

var kraken = {
  age: 9999,
  hasTentacles: true
};

var kar = 9999;

exports.me = me;
exports.you = you;
exports.name = name;
exports.meNextYear = meNextYear;
exports.baby = baby;
exports.getAge = getAge;
exports.kraken = kraken;
exports.me1 = me1;
exports.kar = kar;
/*  Not a pure module */
