// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function RefsAndDOM(Props) {
  var clicks = React.useRef(0);
  var onClick = function (param) {
    clicks.current = clicks.current + 1 | 0;
    
  };
  return React.createElement("div", {
              onClick: onClick
            }, String(clicks.current));
}

function RefsAndDOM$make1(Props) {
  var textInput = React.useRef(null);
  var onClick = function (param) {
    var dom = textInput.current;
    if (!(dom == null)) {
      dom.focus();
      return ;
    }
    
  };
  return React.createElement("div", undefined, React.createElement("input", {
                  ref: textInput,
                  type: "text"
                }), React.createElement("input", {
                  type: "button",
                  value: "Focus the text input",
                  onClick: onClick
                }));
}

var make = RefsAndDOM;

var make1 = RefsAndDOM$make1;

exports.make = make;
exports.make1 = make1;
/* react Not a pure module */
