// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var coordinates2 = [
  60,
  20,
  30
];

function sum(x, y) {
  return x + y | 0;
}

var divide = Caml_int32.div;

function getCalculate(param) {
  var y = 1;
  return [
          6,
          y
        ];
}

var ageAndName = [
  24,
  "Lil' ReScript"
];

var my3dCoordinates = [
  20.0,
  30.5,
  100.0
];

var ageAndName1 = [
  24,
  "Lil' ReScript"
];

var my3dCoordinates1 = [
  20.0,
  30.5,
  100.0
];

var oneTuple = 24;

var y = 30.5;

var coordinates1 = [
  10,
  20,
  30
];

var c1x = 10;

exports.ageAndName = ageAndName;
exports.my3dCoordinates = my3dCoordinates;
exports.ageAndName1 = ageAndName1;
exports.my3dCoordinates1 = my3dCoordinates1;
exports.oneTuple = oneTuple;
exports.y = y;
exports.coordinates1 = coordinates1;
exports.c1x = c1x;
exports.coordinates2 = coordinates2;
exports.sum = sum;
exports.divide = divide;
exports.getCalculate = getCalculate;
/* No side effect */
