// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

var payloadResults = [
  {
    TAG: /* Ok */0,
    _0: {
      data: "hi"
    }
  },
  {
    TAG: /* Ok */0,
    _0: {
      data: "bye"
    }
  },
  {
    TAG: /* Error */1,
    _0: "Something wrong happened!"
  }
];

var seung_friends = [
  {
    name: "test",
    friends: []
  },
  {
    name: "harang",
    friends: []
  }
];

var seung = {
  name: "seungmin",
  friends: seung_friends
};

var myTeacher = {
  taughtBy: {
    students: []
  }
};

var gpa = 2.1 + 10;

var score = 10;

var myScore = 10;

var myInt = 9;

var x = 10;

var a = [
  10,
  20,
  20
];

var b = [
  10.5,
  20.5,
  20.5
];

var buddy = [
  10,
  20,
  20
];

var age = 10;

exports.score = score;
exports.add = add;
exports.myScore = myScore;
exports.myInt = myInt;
exports.x = x;
exports.a = a;
exports.b = b;
exports.buddy = buddy;
exports.payloadResults = payloadResults;
exports.seung = seung;
exports.myTeacher = myTeacher;
exports.age = age;
exports.gpa = gpa;
/* No side effect */
