// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function renderDot(coordinates) {
  console.log("Pretend to draw at:", coordinates.x, coordinates.y);
  
}

function toWorldCoordinates(coordinates) {
  return {
          x: coordinates.x + 10,
          y: coordinates.x + 20
        };
}

var playerLocalCoordinates = {
  x: 20.5,
  y: 30.5
};

renderDot(toWorldCoordinates(playerLocalCoordinates));

var studentName = /* Name */{
  _0: "Joe"
};

var hi = {
  message: "hello!"
};

var studentName1 = "Joe";

var hi1 = "hello!";

exports.studentName = studentName;
exports.hi = hi;
exports.studentName1 = studentName1;
exports.hi1 = hi1;
exports.renderDot = renderDot;
exports.toWorldCoordinates = toWorldCoordinates;
exports.playerLocalCoordinates = playerLocalCoordinates;
/*  Not a pure module */
