// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function UseState(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(setText, (function (_prev) {
                  return value;
                }));
  };
  return React.createElement("div", undefined, React.createElement("input", {
                  value: match[0],
                  onChange: onChange
                }));
}

function UseState$ControlPanel(Props) {
  var setDarkmode = Props.setDarkmode;
  var darkmode = Props.darkmode;
  var onClick = function (evt) {
    evt.preventDefault();
    return Curry._1(setDarkmode, (function (prev) {
                  return !prev;
                }));
  };
  var toggleText = "Switch to " + ((
      darkmode ? "light" : "dark"
    ) + " theme");
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: onClick
                }, toggleText));
}

var ControlPanel = {
  make: UseState$ControlPanel
};

function UseState$make1(Props) {
  var content = Props.content;
  var match = React.useState(function () {
        return false;
      });
  var darkmode = match[0];
  var className = darkmode ? "theme-dark" : "theme-light";
  return React.createElement("div", {
              className: className
            }, React.createElement("section", undefined, React.createElement("h1", undefined, "More Infos about ReScript"), content), React.createElement(UseState$ControlPanel, {
                  setDarkmode: match[1],
                  darkmode: darkmode
                }));
}

var make = UseState;

var make1 = UseState$make1;

exports.make = make;
exports.ControlPanel = ControlPanel;
exports.make1 = make1;
/* react Not a pure module */
